name: thelounge
version: stable
version-script: git -C parts/thelounge/build describe --dirty | sed "s/v//g"
summary:  Modern web IRC client designed for self-hosting.
description: |
 * **Modern features brought to IRC.** Push notifications, link previews, new message markers, and more bring IRC to the 21st century.
 * **Always connected.** Remains connected to IRC servers while you are offline.
 * **Cross platform.** It doesn't matter what OS you use, it just works wherever Node.js runs.
 * **Responsive interface.** The client works smoothly on every desktop, smartphone and tablet.
 * **Synchronized experience.** Always resume where you left off no matter what device.

grade: devel
confinement: strict

environment:
  LOUNGE_HOME: $SNAP_DATA/home

apps:
  lounged:
    command: lounge start
    daemon: simple
    plugs: [network-bind]
  lounge:
    command: lounge
    plugs: [network-bind]

parts:
  thelounge:
    source: https://github.com/thelounge/thelounge
    source-type: git
    plugin: nodejs
    node-package-manager: yarn
    npm-run: [build]
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info thelounge | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi
      snapcraftctl build
      # This is here to avoid a loading issue as defaultHome is called
      # before setting it through program.home or process.env.LOUNGE_HOME
      echo /tmp >> $SNAPCRAFT_PART_INSTALL/node_modules/thelounge/.lounge_home

