name: thelounge
adopt-info: thelounge
summary:  Modern web IRC client designed for self-hosting.
description: |
 * **Modern features brought to IRC.** Push notifications, link previews, new message markers, and more bring IRC to the 21st century.
 * **Always connected.** Remains connected to IRC servers while you are offline.
 * **Cross platform.** It doesn't matter what OS you use, it just works wherever Node.js runs.
 * **Responsive interface.** The client works smoothly on every desktop, smartphone and tablet.
 * **Synchronized experience.** Always resume where you left off no matter what device.

 After installing run the following in a terminal/console:

 `sudo thelounge add $USER`

 Replace `$USER` with your preferred Lounge username. You will be prompted to add a password once you've authenticated for sudo. When you have added your username navigate to http://localhost:9000/ (replace localhost with your server IP or hostname if you are on a different machine) and login with your new username and password.

base: core18
grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

environment:
  LOUNGE_HOME: /var/thelounge

layout:
  /var/thelounge:
    bind: $SNAP_DATA/home

apps:
  lounged:
    command: bin/thelounge start
    daemon: simple
    plugs:
    - network
    - network-bind
  thelounge:
    command: bin/thelounge
    plugs:
    - network
    - network-bind

parts:
  thelounge:
    source: https://github.com/thelounge/thelounge.git
    plugin: nodejs
    nodejs-version: '12.13.0'
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0 --match 'v*' --exclude '*-pre.*' --exclude '*-rc.*')"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version "${last_committed_tag#v}"
      else
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
    override-build: |
      export PATH="$PATH:$SNAPCRAFT_PART_SRC/../npm/bin"
      CMD=yarn
      [ -n "$http_proxy" ] && CMD="$CMD --proxy $http_proxy"
      [ -n "$https_proxy" ] && CMD="$CMD --https-proxy $https_proxy"

      $CMD install
      NODE_ENV=production $CMD build

      snapcraftctl build
    build-packages:
    - build-essential
    - python
    prime:
    - -**/.*.swp # Exclude rogue vim swap files from node-tar package

  hack:
    after: [thelounge]
    plugin: nil
    source: https://github.com/thelounge/thelounge.git
    override-prime: |
      echo /var/thelounge > $SNAPCRAFT_PRIME/.thelounge_home

